### ISSUE TITLE
Problem with build with_data

### ISSUE THREAD

**Issue by jurica** [davesloan/mysql-php-migrations#1]
Hi,
i discovered a small quirk. build with_data doesn't execute test_data.php as it should when there aren't any existing migrations.
It seems like the exit command on line 54 in latest_controller.php is the problem.
Perhaps an initial migration should be created to prevent this behavior?

**Comment by davesloan** [comment]
I'll look into it and release a new tag.  Thanks for bringing it to my attention.

**Comment by davesloan** [comment]
resolved in tag 2.1.1
