### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by d13r** [davesloan/mysql-php-migrations#11]
Currently there's no .gitignore file to ignore the generated config file, so `git status` always shows config/db_config.php as an untracked file.

This is particularly annoying because I'm using git submodules to include this repository inside mine, and this makes the parent repo status always say "modified:   mysql-php-migrations (untracked content)".

Thanks!

**Comment by snpy** [comment]
You could use `git update-index --assume-unchanged` as temporary solution here.

**Comment by d13r** [comment]
@snpy I ended up creating the .gitignore file myself (in a setup script). As long as it ignores itself too Git stops reporting any changes:

```
/.gitignore
/config/db_config.php
```

**Comment by d13r** [comment]
I couldn't figure out how to add a pull request to this issue so see #12.
